# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.postgreswriter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-writer
spec:
  selector:
    app: {{ .Release.Name }}
    component: postgres-writer
  ports:
    - protocol: TCP
      port: {{ .Values.postgresdb.writer.httpPort | int }}
      name: {{ .Release.Name }}-postgreswriter-{{ .Values.postgresdb.writer.httpPort }}
{{- end }}
