# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.postgresreader.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-reader
spec:
  selector:
    app: {{ .Release.Name }}
    component: postgres-reader
  ports:
    - protocol: TCP
      port: {{ .Values.postgresdb.reader.httpPort | int }}
      name: {{ .Release.Name }}-postgresreader-{{ .Values.postgresdb.reader.httpPort }}
{{- end }}
