---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.re.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-re
spec:
  selector:
    app: {{ .Release.Name }}
    component: re
  ports:
    - port: {{ .Values.re.httpPort }}
      protocol: TCP
      name: {{ .Release.Name }}-re-{{ .Values.re.httpPort }}
{{- end }}
