---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.timescaledb.reader.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescaledb-reader
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: timescaledb-reader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: timescaledb-reader
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.timescaledb.reader.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-timescaledb-reader
          image: "{{ default (printf "%s/timescale-reader" .Values.defaults.image.rootRepository) .Values.timescaledb.reader.image.repository }}:{{ default .Values.defaults.image.tag .Values.timescaledb.reader.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.timescaledb.reader.image.pullPolicy }}
          env:
            - name: SMQ_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.timescaledb.reader.sendTelemetry | quote  }}
            - name: MG_TIMESCALE_READER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.timescaledb.reader.logLevel  | quote }}
            - name: MG_TIMESCALE_READER_HTTP_HOST
              value: "0.0.0.0"
            - name: MG_TIMESCALE_READER_HTTP_PORT
              value: {{ .Values.timescaledb.reader.httpPort | quote }}
            - name: MG_TIMESCALE_READER_HTTP_SERVER_CERT
              value: {{ .Values.timescaledb.reader.httpServerCert | quote }}
            - name: MG_TIMESCALE_READER_HTTP_SERVER_KEY
              value: {{ .Values.timescaledb.reader.httpServerKey | quote }}
            - name: SMQ_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.auth.grpcPort }}
            - name: SMQ_CLIENTS_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.clients.authGrpcPort }}
            - name: SMQ_CLIENTS_GRPC_TIMEOUT
              value: {{ .Values.supermq.clients.grpcTimeout | quote }}
            - name: SMQ_CLIENTS_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.clients.grpcClientCert | quote }}
            - name: SMQ_CLIENTS_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.clients.grpcClientKey | quote }}
            - name: SMQ_CLIENTS_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.clients.grpcServerCACerts | quote }}
            - name: SMQ_CHANNELS_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.channels.grpcPort }}
            - name: SMQ_CHANNELS_GRPC_TIMEOUT
              value: {{ .Values.supermq.channels.grpcTimeout | quote }}
            - name: SMQ_CHANNELS_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.channels.grpcClientCert | quote }}
            - name: SMQ_CHANNELS_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.channels.grpcClientKey | quote }}
            - name: SMQ_CHANNELS_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.channels.grpcServerCACerts | quote }}
            - name: SMQ_AUTH_GRPC_TIMEOUT
              value: {{ .Values.supermq.auth.grpcTimeout | quote }}
            - name: SMQ_AUTH_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.auth.grpcClientCert | quote }}
            - name: SMQ_AUTH_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.auth.grpcClientKey | quote }}
            - name: SMQ_AUTH_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.auth.grpcServerCACerts | quote }}
            - name: MG_TIMESCALE_HOST
            {{- if .Values.timescaledb.enabled }}
              value: "{{ .Release.Name }}-timescaledb"
            {{- else }}
              value: {{ .Values.timescaledb.host | quote }}
            {{- end }}
            - name: MG_TIMESCALE_PORT
              value: {{ .Values.timescaledb.port | quote  }}
            - name: MG_TIMESCALE_USER
              value: {{ .Values.timescaledb.username | quote  }}
            - name: MG_TIMESCALE_PASS
              value: {{ .Values.timescaledb.password | quote  }}
            - name: MG_TIMESCALE_NAME
              value: {{ .Values.timescaledb.database | quote }}
            - name: MG_TIMESCALE_SSL_MODE
              value: {{ .Values.timescaledb.sslMode | quote }}
            - name: MG_TIMESCALE_SSL_CERT
              value: {{ .Values.timescaledb.sslCert | quote }}
            - name: MG_TIMESCALE_SSL_KEY
              value: {{ .Values.timescaledb.sslKey | quote }}
            - name: MG_TIMESCALE_SSL_ROOT_CERT
              value: {{ .Values.timescaledb.sslRootCert | quote }}
            - name: MG_TIMESCALE_READER_INSTANCE_ID
              value: {{ .Values.timescaledb.reader.instanceId | quote }}
          ports:
            - containerPort: {{ .Values.timescaledb.reader.httpPort }}
              protocol: TCP
      {{- with .Values.timescaledb.reader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescaledb.reader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescaledb.reader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
