---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.timescalereader.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb-reader
spec:
  selector:
    app: {{ .Release.Name }}
    component: timescaledb-reader
  ports:
    - port: {{ .Values.timescalereader.httpPort | int }}
      protocol: TCP
      name: {{ .Release.Name }}-timescaledb-reader-{{ .Values.timescalereader.httpPort }}
{{- end }}
