---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.timescalereader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-timescaledb-reader
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: timescaledb-reader
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: timescaledb-reader
    spec:
      {{- with (default .Values.defaults.image.pullSecrets .Values.timescalereader.image.pullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}-timescaledb-reader
          image: "{{ default (printf "%s/timescale-reader" .Values.defaults.image.rootRepository) .Values.timescalereader.image.repository }}:{{ default .Values.defaults.image.tag .Values.timescalereader.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.timescalereader.image.pullPolicy }}
          env:
            - name: SMQ_SEND_TELEMETRY
              value: {{ default .Values.defaults.sendTelemetry .Values.timescalereader.sendTelemetry | quote  }}
            - name: MG_TIMESCALE_READER_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.timescalereader.logLevel  | quote }}
            - name: MG_TIMESCALE_READER_HTTP_HOST
              value: "0.0.0.0"
            - name: MG_TIMESCALE_READER_HTTP_PORT
              value: {{ .Values.timescalereader.httpPort | quote }}
            - name: MG_TIMESCALE_READER_HTTP_SERVER_CERT
              value: {{ .Values.timescalereader.httpServerCert | quote }}
            - name: MG_TIMESCALE_READER_HTTP_SERVER_KEY
              value: {{ .Values.timescalereader.httpServerKey | quote }}
            - name: SMQ_AUTH_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.auth.grpcPort }}
            - name: SMQ_CLIENTS_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.clients.authGrpcPort }}
            - name: SMQ_CLIENTS_GRPC_TIMEOUT
              value: {{ .Values.supermq.clients.grpcTimeout | quote }}
            - name: SMQ_CLIENTS_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.clients.grpcClientCert | quote }}
            - name: SMQ_CLIENTS_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.clients.grpcClientKey | quote }}
            - name: SMQ_CLIENTS_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.clients.grpcServerCACerts | quote }}
            - name: SMQ_CHANNELS_GRPC_URL
              value: {{ .Release.Name }}-envoy:{{ .Values.supermq.channels.grpcPort }}
            - name: SMQ_CHANNELS_GRPC_TIMEOUT
              value: {{ .Values.supermq.channels.grpcTimeout | quote }}
            - name: SMQ_CHANNELS_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.channels.grpcClientCert | quote }}
            - name: SMQ_CHANNELS_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.channels.grpcClientKey | quote }}
            - name: SMQ_CHANNELS_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.channels.grpcServerCACerts | quote }}
            - name: SMQ_AUTH_GRPC_TIMEOUT
              value: {{ .Values.supermq.auth.grpcTimeout | quote }}
            - name: SMQ_AUTH_GRPC_CLIENT_CERT
              value: {{ .Values.supermq.auth.grpcClientCert | quote }}
            - name: SMQ_AUTH_GRPC_CLIENT_KEY
              value: {{ .Values.supermq.auth.grpcClientKey | quote }}
            - name: SMQ_AUTH_GRPC_SERVER_CA_CERTS
              value: {{ .Values.supermq.auth.grpcServerCACerts | quote }}
            - name: MG_TIMESCALE_HOST
              value: {{ if and .Values.timescalereader.externaldb.host (not .Values.timescaledbrw.enabled) }}
                        {{- .Values.timescalereader.externaldb.host | quote }}
                      {{- else if .Values.timescaledbrw.enabled }}
                          {{- printf "%s-timescaledbrw" .Release.Name }}
                      {{- else }}
                          {{- fail "either timescaledbrw must be enabled or .Values.timescalereader.externaldb.host must be provided"  }}
                      {{- end }}
            - name: MG_TIMESCALE_PORT
              value: {{ if and .Values.timescalereader.externaldb.port (not .Values.timescaledbrw.enabled) }}
                          {{- .Values.timescalereader.externaldb.port | quote }}
                      {{- else if .Values.timescaledbrw.enabled }}
                          {{- .Values.timescaledbrw.global.postgresql.service.ports.postgresql | quote }}
                      {{- else }}
                          {{- fail "either timescaledbrw must be enabled or .Values.timescalereader.externaldb.port must be provided"  }}
                      {{- end }}
            - name: MG_TIMESCALE_USER
              value: {{ if and .Values.timescalereader.externaldb.username (not .Values.timescaledbrw.enabled) }}
                          {{- .Values.timescalereader.externaldb.username | quote }}
                      {{- else if .Values.timescaledbrw.enabled }}
                          {{- .Values.timescaledbrw.global.postgresql.auth.username | quote }}
                      {{- else }}
                          {{- fail "either timescaledbrw must be enabled or .Values.timescalereader.externaldb.username must be provided"  }}
                      {{- end }}
            - name: MG_TIMESCALE_PASS
              value: {{ if and .Values.timescalereader.externaldb.password (not .Values.timescaledbrw.enabled) }}
                          {{- .Values.timescalereader.externaldb.password | quote }}
                      {{- else if .Values.timescaledbrw.enabled }}
                          {{- .Values.timescaledbrw.global.postgresql.auth.password | quote }}
                      {{- else }}
                          {{- fail "either timescaledbrw must be enabled or .Values.timescalereader.externaldb.password must be provided"  }}
                      {{- end }}
            - name: MG_TIMESCALE_NAME
              value: {{ if and .Values.timescalereader.externaldb.database (not .Values.timescaledbrw.enabled) }}
                          {{- .Values.timescalereader.externaldb.database | quote }}
                      {{- else if .Values.timescaledbrw.enabled }}
                          {{- .Values.timescaledbrw.global.postgresql.auth.database | quote }}
                      {{- else }}
                          {{- fail "either timescaledbrw must be enabled or .Values.timescalereader.externaldb.database must be provided"  }}
                      {{- end }}
            - name: MG_TIMESCALE_SSL_MODE
              value: {{ .Values.timescalereader.externaldb.sslMode | default "" | quote }}
            - name: MG_TIMESCALE_SSL_CERT
              value: {{ .Values.timescalereader.externaldb.sslCert | default "" | quote }}
            - name: MG_TIMESCALE_SSL_KEY
              value: {{ .Values.timescalereader.externaldb.sslKey | default "" | quote }}
            - name: MG_TIMESCALE_SSL_ROOT_CERT
              value: {{ .Values.timescalereader.externaldb.sslRootCert | default "" | quote }}
            - name: MG_TIMESCALE_READER_INSTANCE_ID
              value: {{ .Values.timescalereader.instanceId | quote }}
          ports:
            - containerPort: {{ .Values.timescalereader.httpPort }}
              protocol: TCP
      {{- with .Values.timescalereader.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescalereader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.timescalereader.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
