---
# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

supermq:
  enabled: true
  ingress:
    enabled: true
    ## Uncomment this block for TLS support in public ingress
    # annotations:
    #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #   cert-manager.io/issuer: "letsencrypt-staging"

    ## Uncomment this block for TLS support in public ingress
    hostname: "localhost"
    # tls:
    #   hostname: "stage.magistrala.abstractmachines.fr"
    #   secret: "letsencrypt-staging-certificate-secret"
  ui:
    type: "mg"
    image:
      repository: "ghcr.io/absmach/magistrala/ui-mg"
  auth:
    grpcServerCACerts: ""

  clients:
    grpcServerCACerts: ""

  nginx:
    hostname: "localhost"

defaults:
  image:
    pullPolicy: "IfNotPresent"
    rootRepository: "ghcr.io/absmach/magistrala"
    tag: "latest"
    # pullSecrets: {}
  logLevel: "error"
  sendTelemetry: "true"
  replicaCount: 1

bootstrap:
  enabled: true
  image: {}
  #   pullSecrets: {}
  #   repository: "ghcr.io/absmach/magistrala/bootstrap"
  #   tag: "latest"
  #   pullPolicy: "IfNotPresent"
  # sendTelemetry: true
  # logLevel: "error"
  jaegerTraceRatio: 1.0
  replicaCount: 1
  httpPort: 9013
  encKey: "v7aT0HGxJxt2gULzr3RHwf4WIf6DusPp"
  eventConsumer: bootstrap
  httpServerCert: ""
  httpServerKey: ""
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

postgresqlbootstrap:
  ## If you want to use an external database, set this to false and change host & port to external postgresql server host & port respectively
  enabled: true
  name: postgresql-bootstrap
  host: postgresql-bootstrap
  port: &postgresqlBootstrapPort 5432
  database: &postgresqlBootstrapDatabase bootstrap
  username: &postgresqlBootstrapUsername magistrala
  password: &postgresqlBootstrapPassword magistrala
  sslMode: "disable"
  sslCert: ""
  sslKey: ""
  sslRootCert: ""
  global:
    postgresql:
      auth:
        postgresPassword: *postgresqlBootstrapPassword
        username: *postgresqlBootstrapUsername
        password: *postgresqlBootstrapPassword
        database: *postgresqlBootstrapDatabase
      service:
        ports:
          postgresql: *postgresqlBootstrapPort
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "150m"
        memory: "192Mi"
    persistence:
      enabled: true
      size: 2Gi

re:
  enabled: true
  image: {}
    # repository: "ghcr.io/absmach/magistrala/re"
    # tag: "latest"
    # pullPolicy: "IfNotPresent"
  # jaegerTraceRatio: 1.0
  # logLevel: "error"
  # sendTelemetry: "true"
  replicaCount: 1
  httpPort: 9008
  httpServerCert: ""
  httpServerKey: ""
  grpcTimeout: "300s"
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

postgresqlre:
  enabled: true
  name: postgresql-re
  host: postgresql-re
  port: &postgresqlRePort 5432
  database: &postgresqlReDatabase rules_engine
  username: &postgresqlReUsername magistrala
  password: &postgresqlRePassword magistrala
  sslMode: "disable"
  sslCert: ""
  sslKey: ""
  sslRootCert: ""
  global:
    postgresql:
      auth:
        postgresPassword: *postgresqlRePassword
        username: *postgresqlReUsername
        password: *postgresqlRePassword
        database: *postgresqlReDatabase
      service:
        ports:
          postgresql: *postgresqlRePort
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "150m"
        memory: "192Mi"
    persistence:
      enabled: true
      size: 2Gi

provision:
  enabled: true
  image:
    {}
    # pullSecrets: {}
    # repository: "ghcr.io/absmach/magistrala/provision"
    # tag: "latest"
    # pullPolicy: "IfNotPresent"
  # sendTelemetry: "true"
  # logLevel: "error"
  replicaCount: 1
  httpPort: 9016
  configFile: "/configs/config.toml"
  envClientsTLS: "false"
  serverCert: ""
  serverKey: ""
  user: ""
  username: ""
  password: ""
  apiKey: ""
  usersUrl: "http://users:9002"
  clientsUrl: "http://clients:9006"
  certsUrl: "http://certs:9019"
  bootstrapUrl: "http://bootstrap:9013"
  bsConfigProvisioning: "true"
  bsAutoWhitelist: "true"
  bsContent: ""
  x509Provisioning: "false"
  certsHoursValid: "2400h"
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

postgresreader:
  enabled: false
  image: {}
    # repository: "ghcr.io/absmach/magistrala/postgres-reader"
    # tag: "latest"
    # pullPolicy: IfNotPresent
  # sendTelemetry: "true"
  # logLevel: "error"
  externaldb:
    {}
  #   host: postgresdbrw
  #   port: 5432
  #   database: supermq
  #   username: supermq
  #   password: supermq
  #   sslMode: ""
  #   sslCert: ""
  #   sslKey: ""
  #   sslRootCert: ""
  replicaCount: 1
  httpPort: "9009"
  httpServerCert: ""
  httpServerKey: ""
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

postgreswriter:
  enabled: false
  image: {}
    # repository: "ghcr.io/absmach/magistrala/postgres-writer"
    # tag: "latest"
    # pullPolicy: IfNotPresent
  # logLevel: "error"
  externaldb:
    {}
  #   host: postgresdbrw
  #   port: 5432
  #   database: supermq
  #   username: supermq
  #   password: supermq
  #   sslMode: ""
  #   sslCert: ""
  #   sslKey: ""
  #   sslRootCert: ""
  jaegerTraceRatio: 1.0
  sendTelemetry: "true"
  replicaCount: 1
  configPath: "/config.toml"
  httpPort: "9010"
  httpServerCert: ""
  httpServerKey: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

postgresdbrw:
  # If you want to use an external database, set this to false and change host & port to external postgresql server host & port respectively
  enabled: false
  global:
    postgresql:
      auth:
        postgresPassword: supermq
        username: supermq
        password: supermq
        database: messages
      service:
        ports:
          postgresql: 5432
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "150m"
        memory: "192Mi"
    persistence:
      enabled: true
      size: 2Gi

timescalereader:
  enabled: true
  image: {}
    # pullSecrets: {}
    # repository: "ghcr.io/absmach/magistrala/timescale-reader"
    # tag: "latest"
    # pullPolicy: "IfNotPresent"
  # jaegerTraceRatio: 1.0
  # sendTelemetry: true
  # logLevel: "error"
  externaldb:
    {}
  #   host: timescaledbrw
  #   port: 5432
  #   database: supermq
  #   username: supermq
  #   password: supermq
  #   sslMode: ""
  #   sslCert: ""
  #   sslKey: ""
  #   sslRootCert: ""
  httpPort: 9011
  httpServerCert: ""
  httpServerKey: ""
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

timescalewriter:
  enabled: true
  image: {}
    # pullSecrets: {}
    # repository: "ghcr.io/absmach/magistrala/timescale-writer"
    # tag: "latest"
    # pullPolicy: "IfNotPresent"
  # jaegerTraceRatio: 1.0
  # sendTelemetry: true
  # logLevel: "error"
  externaldb:
    {}
  #   host: timescaledbrw
  #   port: 5432
  #   database: supermq
  #   username: supermq
  #   password: supermq
  #   sslMode: ""
  #   sslCert: ""
  #   sslKey: ""
  #   sslRootCert: ""
  httpPort: 9012
  httpServerCert: ""
  httpServerKey: ""
  instanceId: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  # nodeSelector: {}
  # affinity: {}
  # tolerations: {}

timescaledbrw:
  ## If you want to use an external database, set this to false and set value for externaldb in both timescalewriter and timescalereader.
  enabled: true
  ## Configurations of Bitnami postgres
  global:
    postgresql:
      auth:
        postgresPassword: supermq
        username: supermq
        password: supermq
        database: &timescaledbrwDatabase messages
      service:
        ports:
          postgresql: 5432
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "150m"
        memory: "192Mi"

    extraEnvVars:
      - name: TIMESCALEDB_TELEMETRY
        value: "off"
      - name: POSTGRES_DB
        value: *timescaledbrwDatabase
    persistence:
      enabled: true
      size: 2Gi
    extraVolumeMounts:
      - name: postgresql-run
        mountPath: /var/run/postgresql
    extraVolumes:
      - name: postgresql-run
        emptyDir: {}
  image:
    registry: docker.io
    repository: timescale/timescaledb
    tag: latest-pg16
    debug: true
